name: Spell checker
description: checks spelling of all markdown files
author: https://github.com/billyschmidt
requirements: []
configuration:
  properties:
    pattern: 
      type: string
  required:
    - pattern
